build:
  image: gcc:latest
  commands:
    - mkdir -p build
    - cd build
    - apt-get update
    - apt-get -y install cmake lcov
    - cmake -DSHINZUI_BUILD_TESTS=ON -DSHINZUI_COVERAGE=ON ..
    - make ShinzuiCoverage
    - cp coverage.info.cleaned ../lcov.info

cache:
  mount:
    - build

publish:
  coverage:
    token: b57f6ae8c1396a429a703cbbe14979e8d53e64c9
    server: http://g-build-server.asuscomm.com:8001
    include: lcov.info
